checks:
    php:
        avoid_closing_tag: true
        verify_property_names: true
        verify_access_scope_valid: true
        variable_existence: true
        useless_calls: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        use_statement_alias_conflict: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        single_namespace_per_use: true
        return_doc_comment_if_not_inferrable: true
        require_php_tag_first: true
        require_scope_for_methods: true
        require_scope_for_properties: true
        require_braces_around_control_structures: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        prefer_sapi_constant: true
        php5_style_constructor: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_unnecessary_final_modifier: true
        no_unnecessary_function_call_in_for_loop: true
        no_trait_type_hints: true
        no_trailing_whitespace: true
        no_space_inside_cast_operator: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_short_open_tag: true
        no_mixed_inline_html: true
        no_exit: true
        no_eval: true
        no_error_suppression: true
        no_empty_statements: true
        no_else_if_statements: true
        no_debug_code: true
        no_commented_out_code: true
        newline_at_end_of_file: true
        lowercase_php_keywords: true
        lowercase_basic_constants: true
        function_in_camel_caps: true
        function_body_start_on_new_line: true
        ensure_lower_case_builtin_functions: true
        encourage_shallow_comparison: true
        duplication: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        code_rating: true
        classes_in_camel_caps: true
        blank_line_after_namespace_declaration: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_tab_indentation: true
        avoid_superglobals: true
        avoid_multiple_statements_on_same_line: true

tools:
    external_code_coverage: true

filter:
    excluded_paths:
        - Tests/*
